CrudProject/urls.py
from django.contrib import admin
from django.urls import path
from crudapp import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('home/',views.read_data ),
    path('home/<int:id>',views.readone_data),
    path('stud', views.stud),  
    path('show',views.show), 

    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  


]

crudapp/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name=models.CharField(max_length=200)
    branch=models.CharField(max_length=300)
    rollno=models.IntegerField()
    city=models.CharField(max_length=50)
    mobileno=models.IntegerField()

crudapp/forms.py
from django import forms  
from .models import Student 

class StudentForm(forms.ModelForm):  
    class Meta:  
        model = Student  
        fields = "__all__"  

crudapp/views.py
from django.shortcuts import render, redirect 
from crudapp.models import Student
from crudapp.forms import StudentForm

# Create your views here.




def read_data(request):
    Student_list=Student.objects.all()
    employees = Student.objects.all() 

    return render(request,"home.html",{'student_list':employees})

def readone_data(request,id):#id=5
    student=Student.objects.get(id=id)
    context={
        'student':student
    }
    return render(request,"readone.html",context)

def stud(request):  
    if request.method == "POST":  
        form = StudentForm(request.POST)  #form.py
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = StudentForm()  
    return render(request,'index.html',{'form':form})  #index.html

def show(request):  
    employees = Student.objects.all()  
    return render(request,"show.html",{'employees':employees})  

def edit(request, id):  
    employee = Student.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})  
    
def update(request, id):  
    employee = Student.objects.get(id=id)  
    form = StudentForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'employee': employee})  

def destroy(request, id):  
    employee = Student.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")  

crudapp/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="name" id="id_name" required maxlength="20" value="{{ employee.name }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Branch:</label>  
    <div class="col-sm-4">  
        <input type="text" name="branch" id="id_branch" required maxlength="100" value="{{ employee.branch }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Roll No.:</label>  
    <div class="col-sm-4">  
        <input type="number" name="rollno" id="id_rollno" required maxlength="254" value="{{ employee.rollno }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">City:</label>  
    <div class="col-sm-4">  
        <input type="text" name="city" id="id_city" required maxlength="15" value="{{ employee.city }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Mobile No. :</label>  
    <div class="col-sm-4">  
        <input type="number" maxlength="10" name="mobileno" id="id_mobileno" required maxlength="15" value="{{ employee.mobileno }}" />  
    </div>  
  </div>  

    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

crudapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container" align="center">
        <table border="2px" class="table table-striped table-hover">
            <thead  class="thead-dark"> 
                <th><h6>name</h6></th>
                <th><h6>branch</h6></th>
                <th><h6>rollno</h6></th>
                <th><h6>city</h6></th>
                <th><h6>mobno</h6></th>
            </thead>
            {% for i in student_list %}
            <tr>
                <td><h6>{{i.name}}</h6></td>
                <td><h6>{{i.branch}}</h6></td>
                <td><h6>{{i.rollno}}</h6></td>
                <td><h6>{{i.city}}</h6></td>
                <td><h6>{{i.mobileno}}</h6></td>
            </tr>
            {% endfor %}
        </table>
    </div>
    
</body>
</html>

crudapp/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    
</head>  
<body>  
  
<form method="POST" class="post-form" action="/stud">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Name:</label>  
    <div class="col-sm-4">  
      {{ form.name }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student branch:</label>  
    <div class="col-sm-4">  
      {{ form.branch }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Rollno:</label>  
    <div class="col-sm-4">  
      {{ form.rollno }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">City:</label>  
    <div class="col-sm-4">  
      {{ form.city }}  
    </div>  
  </div>  

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Mobile No:</label>  
    <div class="col-sm-4">  
      {{ form.mobileno }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

crudapp/templates/readone.html
!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <ul>

        <li><h4>{{student.name}}</h4></li>
        <li><h4>{{student.branch}}</h4></li>
        <li><h4>{{student.rollno}}</h4></li>
        <li><h4>{{student.city}}</h4></li>
        <li><h4>{{student.mobno}} </h4></li>
    </ul>
    
     
</body>
</html>

crudapp/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
    
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
      
        <th>Name</th>  
        <th>Branch</th>  
        <th>rollno</th>  
        <th>City</th>  
        <th>Mobile</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}  
    <tr>  
        <td>{{ employee.name }}</td>  
        <td>{{ employee.branch }}</td>  
        <td>{{ employee.rollno }}</td>  
        <td>{{ employee.city }}</td>  
        <td>{{ employee.mobileno }}</td>  
        <td>  
                                                         
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ employee.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/stud" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  